kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 192.168.50.40
    worker:
      hosts:
        k8s-1:
          ansible_host: 192.168.50.41
        k8s-2:
          ansible_host: 192.168.50.42
        k8s-3:
          ansible_host: 192.168.50.43
        k8s-4:
          ansible_host: 192.168.50.44
